networks:
  backend-network:
    driver: bridge

services:
  taskboard-keycloak-db-boot:
    image: postgres:15
    container_name: taskboard-keycloak-db-boot
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-storage:/var/lib/postgresql/data
    networks:
      - backend-network

  taskboard-keycloak-boot:
    image: quay.io/keycloak/keycloak:25.0
    container_name: taskboard-keycloak-boot
    restart: always
    depends_on:
      - taskboard-keycloak-db-boot
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://taskboard-keycloak-db-boot/keycloak
      KC_HOSTNAME: taskboard-keycloak-boot
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./config/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - backend-network

  taskboard-service-db-boot:
    image: postgres:15
    container_name: taskboard-service-db-boot
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - service-storage:/var/lib/postgresql/data
    networks:
      - backend-network

  taskboard-service-boot:
    image: ghcr.io/niolikon/taskboard-service-boot:0.0.3
    container_name: taskboard-service-boot
    restart: always
    depends_on:
      - taskboard-service-db-boot
      - taskboard-keycloak-boot
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://taskboard-service-db-boot:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_SERVER_URL: http://taskboard-keycloak-boot:8080
    networks:
      - backend-network

  taskboard-authenticator-boot:
    image: ghcr.io/niolikon/taskboard-authenticator-boot:0.0.2
    container_name: taskboard-authenticator-boot
    restart: always
    depends_on:
      - taskboard-keycloak-boot
    env_file:
      - .env
    environment:
      KEYCLOAK_SERVER_URL: http://taskboard-keycloak-boot:8080
    networks:
      - backend-network

  taskboard-apisix-boot:
    image: apache/apisix:3.11.0-debian
    container_name: taskboard-apisix-boot
    restart: always
    volumes:
      - ./config/apisix/apisix-standalone.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./config/apisix/config-standalone.yaml:/usr/local/apisix/conf/config.yaml
    environment:
      - APISIX_STAND_ALONE=true
    ports:
      - "8080:9080/tcp"
      - "9180:9180/tcp"
    networks:
      - backend-network

  taskboard-app-ng:
    image: ghcr.io/niolikon/taskboard-app-ng:0.0.1
    container_name: taskboard-app-ng
    restart: always
    depends_on:
      - taskboard-apisix-boot
    env_file:
      - .env
    environment:
      TASKBOARD_BACKEND_BASEURL: ${BACKEND_BASEURL}
    networks:
      - backend-network
    ports:
      - "80:80/tcp"

volumes:
  service-storage:
  keycloak-storage:
